use ExtUtils::MakeMaker;

WriteMakefile(
    NAME          => 'corelist web',
    AUTHOR        => 'Some Person <person@example.com>',
    VERSION_FROM  => 'app.psgi',
    PREREQ_PM     => {
        'Amon2'                           => '2.44',
        'Text::Xslate'                    => '1.1005',
        'Text::Xslate::Bridge::TT2Like'   => '0.00008',
        'Plack::Middleware::ReverseProxy' => '0.09',
        'Time::Piece'                     => '1.20',
		'Module::CoreList'                => '2.58',
		JSON => 2,
		(map { $_ => 0 } qw(Plack Router::Simple::Sinatraish Test::WWW::Mechanize::PSGI parent)),
    },
    MIN_PERL_VERSION => '5.008001',
    (-d 'xt' and $ENV{AUTOMATED_TESTING} || $ENV{RELEASE_TESTING}) ? (
        test => {
            TESTS => 't/*.t xt/*.t',
        },
    ) : (),
);
